### ISSUE TITLE
little bit of formatting with up and down indicators

### ISSUE THREAD

**Issue by prashantwosti** [chiehmin/Xposed-NetworkSpeedIndicator#90]
SMALL_UP_TRIANGLE was missing a space in the front so I had to checkout your project to make it align perfectly. Now it looks lot better.

BEFORE:

    public static final String SMALL_UP_TRIANGLE = "\u25B4";
    public static final String SMALL_DOWN_TRIANGLE = " \u25BE ";

AFTER:
         
    public static final String SMALL_UP_TRIANGLE = " \u25B4";
    public static final String SMALL_DOWN_TRIANGLE = " \u25BE";

Small things does matter. ;)

**Comment by ADTC** [comment]
@liu-yun Does this work fine? I saw your pull request. I can merge it.

**Comment by ADTC** [comment]
> ... was missing a space ...
> ... Now it looks lot better.

You're talking about the actual notification bar display right? Not the source code.

**Comment by prashantwosti** [comment]
alright.

**Comment by liu-yun** [comment]
It should work. Only changed 2 strings.
@ADTC See the screenshot: http://imgur.com/snIyKFj

**Comment by ADTC** [comment]
Is your screenshot old (before) or new (after)?

**Comment by liu-yun** [comment]
@ADTC It's old. The patch fixes it.
